### ISSUE TITLE
Separate HTML grid for days of the week

### ISSUE THREAD

**Issue by nickalbrecht** [Eonasdan/tempus-dominus#2609]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=label%3A%22Type%3A+feature+request%22+) for duplicate or closed feature requests.
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Proposal

Split out the grid elements that contain the days of the week into a stand alone grid, separate from the calendar dates to allow for styling those cells' dimensions differently than the calendar dates' cells

### Motivation and context

I'm trying to find a way to shrink the height of the of the cells used to display the day of the week. They're not interactive elements and don't require that much height, and I think they are taller than the older version of TD had them? But I can't find a way to shrink them because of them being in the same grid that is used for the actual dates on the calendar

**Comment by Eonasdan** [comment]
They all have a `dow` css class. I'll look into this.

**Comment by nickalbrecht** [comment]
They do have the `dow` class, but I didn't have any luck at all trying to find CSS that would let me change the amount of height that those cells used. It seemed like the parent element's grid settings were overriding anything I tried. I could be wrong, I don't have much experience with CSS grids. But having them as a separate grid before the calendar days seemed to be the only work around I could find.

**Comment by Eonasdan** [comment]
I know you opened this a looong time ago but here's how you could adjust this

```css
.tempus-dominus-widget .date-container-days {
    display: grid;
    grid-template-areas: "a a a a a a a";
    grid-template-rows: 10px; //since the first row is the days of the week, this will set that row to 10px
    grid-auto-rows: 40px; //everything else stays the same at 40
    grid-auto-columns: 14.2857142857%;
}
```

You really only need the one line `grid-template-rows: 10px;`. Obviously, adjust the 10 to be w/e you need.
